// @ts-nocheck
/**
 * Closed evidence and decision formats for the direct `mcpServer/tool/call`
 * feasibility probe. This module owns `<run>/events.jsonl` (append-only,
 * mode 0600, one flat record per line) and validates the frozen decision
 * record consumed by the final report. It is fixed BEFORE any live Host
 * collection: later tasks may select outcomes from the closed vocabularies
 * below but must never add event kinds or open the field allowlists.
 *
 * Record shape: `{version:1, runNonce, sequence, phase, kind, ...kindFields}`.
 * `probeLabel` is a fresh random diagnostic label unique inside the run and
 * `callNonce` is generated by the handler and first appears in
 * `handler-entered`; neither value grants authority. A driver event refers to
 * a callNonce only after a durable join on one unique probeLabel in the run
 * and bounded phase, and the reducer refuses to interpret a driver record as
 * proof of handler or worker settlement. Only closed enums, booleans, bounded
 * counters, field-name/type pairs, and per-run salted hashes are permitted —
 * no generic spread, arbitrary payload, raw ID, or raw path. Null is
 * permitted only where the contract explicitly allows absence
 * (`rpc-observed.callNonce` may be absent until entry; `candidateHashes`
 * values record absence as null).
 *
 * Low-level durable log IO lives in the private `probe-log.mjs` helper;
 * this module owns the vocabulary and the two remaining public write/read
 * surfaces: the driver-scoped appender (which rejects every handler-side
 * kind outright) and the locked reader. The handler-scoped writer is NOT
 * exported from this module — it is a per-instance capability minted inside
 * `createDirectProbeServer` (server.mjs), so driver-side code cannot append
 * handler evidence without instantiating a server.
 *
 * Low-level append/hash/file-lock primitives are reused unchanged from
 * `tools/mcp-context-probe/observer.mjs` and `scripts/lib/fs.mjs`; that
 * module's own schema is not modified.
 */
import { hashProbeValue } from '../mcp-context-probe/observer.mjs';
import {
  appendDirectProbeLogRecord,
  DIRECT_PROBE_EVENTS_MAX_BYTES,
  readCommittedDirectProbeLog,
  readDirectProbeLog,
  verifyDirectProbeHandlerOwnership,
  verifyHandlerRecordMacs,
} from './probe-log.mjs';

/** The driver's last-known commit per run directory (writer-held state). */
const driverCommitStates = new Map();

export { hashProbeValue };

/** Maximum accepted size of the JSONL event log in bytes. */
export { DIRECT_PROBE_EVENTS_MAX_BYTES };

/** The closed probe phase vocabulary (bounded phases for the durable join). */
export const DIRECT_PROBE_PHASES = Object.freeze(['reachability', 'identity', 'lifecycle', 'entry']);

/**
 * The complete closed event-kind union, in contract order. This list is the
 * fixed Task 2 contract: later tasks select outcomes from the per-kind enums
 * but NEVER add kinds, so the vocabulary is frozen and deep-equality tested.
 */
export const DIRECT_EVENT_KINDS = Object.freeze([
  'request-sent', 'server-started', 'readiness-observed', 'turn-state-observed', 'handler-entered',
  'metadata-observed', 'hold-started', 'trigger-sent', 'trigger-observed', 'handler-settled',
  'worker-settled', 'rpc-observed', 'entry-action-observed', 'terminal-delivered', 'cleanup-observed',
]);

/** The closed reduced RPC classifications (Task 3 selects from these). */
export const DIRECT_RPC_CLASSIFICATIONS = Object.freeze([
  'rpc-rejected', 'error-result-handler-entered', 'error-result-unknown-origin',
  'success-handler-entered', 'success-unknown-origin', 'not-observed',
]);

/** The closed result-record gate keys and statuses. */
export const DIRECT_GATE_KEYS = Object.freeze(['G1', 'G2', 'G3', 'G4']);
export const DIRECT_GATE_STATUSES = Object.freeze(['proven', 'not-proven', 'incompatible-under-tested-conditions']);

/** The closed provenance fields of the result record (no raw identity). */
export const DIRECT_PROVENANCE_FIELDS = Object.freeze([
  'runNonce', 'codexVersion', 'codexBinaryDigest', 'platform', 'sdkVersion', 'sourceCommit', 'schemaDigest', 'fixtureMode',
  'model', 'effort', 'configurationDigest',
]);

/**
 * The provenance fields required only "where applicable" (spec: model/effort
 * and the sanitized effective configuration). They may be absent — a fixture
 * with no model turn records none — but when present they are validated, and
 * the sanitized configuration enters only as a digest, never as values.
 */
export const DIRECT_OPTIONAL_PROVENANCE_FIELDS = Object.freeze(['model', 'effort', 'configurationDigest']);

/** The closed fixture modes recorded as provenance. */
export const DIRECT_FIXTURE_MODES = Object.freeze(['reachability', 'identity', 'lifecycle', 'entry', 'campaign']);

/** The disposable probe tools a driver may dispatch. */
const DIRECT_TOOLS = Object.freeze(['capture_direct', 'hold_direct']);

/**
 * The closed writer partition of the event union. The disposable server's
 * locked append path writes the handler-side kinds; the driver writes the
 * driver-side kinds. THE PROHIBITION, STATED EXPLICITLY: the driver must
 * never append `handler-entered`, `metadata-observed`, `hold-started`,
 * `handler-settled`, or `worker-settled` — settlement records carry no
 * source field (the contract is fixed), so the only enforcement is
 * structural, and the appender rejects any settlement record whose durable
 * handler-side prerequisites (entry, and a matching hold for the worker)
 * are absent from the log. A settlement that passes the durable call join
 * is attributed in the reduced output to its exact record sequence.
 */
export const DIRECT_HANDLER_EVENT_KINDS = Object.freeze([
  'server-started', 'handler-entered', 'metadata-observed', 'hold-started', 'handler-settled', 'worker-settled',
]);
export const DIRECT_DRIVER_EVENT_KINDS = Object.freeze([
  'request-sent', 'readiness-observed', 'turn-state-observed',
  'trigger-sent', 'trigger-observed', 'rpc-observed',
  'entry-action-observed', 'terminal-delivered', 'cleanup-observed',
]);

/** The closed per-kind enum vocabularies selected by later tasks. */
const DIRECT_REQUEST_STATES = Object.freeze(['sent', 'not-sent']);
const DIRECT_READINESS_STATES = Object.freeze(['discovered', 'missing', 'failed', 'not-observed']);
const DIRECT_TURN_STATES = Object.freeze(['active', 'completed', 'interrupted', 'failed', 'unknown', 'not-observed']);
const DIRECT_METADATA_STATES = Object.freeze(['missing', 'malformed', 'complete']);
const DIRECT_TRIGGER_SENT_OUTCOMES = Object.freeze(['turn-interrupt', 'connection-close', 'config-timeout', 'safety-deadline', 'completion', 'not-sent']);
const DIRECT_TRIGGER_OBSERVED_OUTCOMES = Object.freeze(['acknowledged', 'rejected', 'not-observed']);
const DIRECT_SETTLEMENT_OUTCOMES = Object.freeze(['completed', 'cancelled', 'connection-closed', 'host-exited', 'host-lost', 'timed-out', 'safety-deadline', 'failed', 'not-observed']);
const DIRECT_RPC_OUTCOMES = Object.freeze(['success-result', 'error-result', 'rpc-rejected', 'not-observed']);
const DIRECT_ENTRY_ACTION_OUTCOMES = Object.freeze(['action-dispatched', 'route-missing', 'not-observed']);
const DIRECT_DELIVERY_OUTCOMES = Object.freeze(['delivered', 'not-delivered', 'not-observed']);
const DIRECT_CLEANUP_OUTCOMES = Object.freeze(['released', 'release-failed', 'not-observed']);
const DIRECT_SOURCES = Object.freeze(['driver', 'host', 'transport', 'handler', 'worker', 'unknown']);
const DIRECT_CANDIDATE_KEYS = Object.freeze(['envelopeThreadId', 'innerSessionId', 'innerThreadId', 'innerTurnId']);

const RUN_NONCE_PATTERN = /^[0-9a-f]{64}$/;
/** The closed probeLabel shape: a fresh random diagnostic label, unique per run. */
export const DIRECT_PROBE_LABEL_PATTERN = /^[0-9a-f]{32}$/;
const DIRECT_CALL_NONCE_PATTERN = /^[0-9a-f]{32}$/;
const DIRECT_HASH_PATTERN = /^[0-9a-f]{64}$/;
const DIRECT_REASON_CODE_PATTERN = /^[a-z][a-z0-9-]{0,63}$/;
const DIRECT_EVIDENCE_REF_PATTERN = /^[a-z][a-z0-9-]*@[0-9]{1,6}$/;
const DIRECT_SOURCE_COMMIT_PATTERN = /^[0-9a-f]{40}$/;
const DIRECT_SEQUENCE_BOUND = 1_000_000;
const MAXIMUM_META_FIELD_ENTRIES = 32;

/**
 * The closed field-name vocabulary of a metadata fingerprint: only the
 * allowlisted candidate paths and the redaction token. A metadata key
 * containing a path, credential, or raw identifier can therefore never
 * enter the evidence — unknown top-level names are recorded only as
 * `[redacted]` (their JSON type is kept), and nested names other than the
 * allowlisted candidate paths are not recorded at all.
 */
export const DIRECT_METADATA_FIELD_NAMES = Object.freeze([
  'threadId',
  'x-codex-turn-metadata',
  'x-codex-turn-metadata.session_id',
  'x-codex-turn-metadata.thread_id',
  'x-codex-turn-metadata.turn_id',
  '[redacted]',
]);

/** The closed JSON type-name vocabulary of a metadata fingerprint. */
export const DIRECT_FIELD_TYPE_NAMES = Object.freeze(['string', 'number', 'boolean', 'object', 'array', 'null', 'unknown']);

/** The exact additional permitted fields per kind (the fixed contract table). */
/**
 * The exact additional permitted fields per kind (the fixed contract table).
 * The six handler-side kinds additionally carry the required `recordMac`
 * HMAC (see the per-record authentication note on DIRECT_HANDLER_EVENT_KINDS).
 */
const KIND_ALLOWED_FIELDS = Object.freeze({
  'request-sent': Object.freeze(['probeLabel', 'tool', 'state']),
  'server-started': Object.freeze(['serverInstanceHash', 'recordMac']),
  'readiness-observed': Object.freeze(['state', 'source']),
  'turn-state-observed': Object.freeze(['threadHash', 'turnHash', 'state', 'source']),
  'handler-entered': Object.freeze(['probeLabel', 'callNonce', 'serverInstanceHash', 'recordMac']),
  'metadata-observed': Object.freeze(['callNonce', 'fields', 'fieldsTruncated', 'candidateHashes', 'state', 'recordMac']),
  'hold-started': Object.freeze(['callNonce', 'workerHash', 'recordMac']),
  'trigger-sent': Object.freeze(['callNonce', 'outcome']),
  'trigger-observed': Object.freeze(['callNonce', 'outcome', 'source']),
  'handler-settled': Object.freeze(['callNonce', 'outcome', 'recordMac']),
  'worker-settled': Object.freeze(['callNonce', 'workerHash', 'outcome', 'recordMac']),
  'rpc-observed': Object.freeze(['probeLabel', 'callNonce', 'outcome']),
  'entry-action-observed': Object.freeze(['probeLabel', 'outcome', 'source']),
  'terminal-delivered': Object.freeze(['probeLabel', 'outcome', 'source']),
  'cleanup-observed': Object.freeze(['outcome', 'source']),
});

/** @param {string} code @param {string} message */
function directError(code, message) {
  // The code is embedded in the message (the entry-inventory convention) so
  // closed-code assertions can match failures textually as well as via .code.
  const error = /** @type {Error & {code:string}} */ (new Error(`${code}: ${message}`));
  error.code = code;
  return error;
}

/** @param {string} value */
function isBoundedText(value) {
  // The regex deliberately matches control characters: rejecting them is the
  // entire purpose of this check.
  // eslint-disable-next-line no-control-regex
  return typeof value === 'string' && value.length > 0 && value.length <= 4096 && !/[\u0000-\u001f\u007f]/.test(value);
}

/** @param {string} nonce */
function requireRunNonce(nonce) {
  if (!RUN_NONCE_PATTERN.test(nonce)) throw directError('PROBE_NONCE_INVALID', 'The probe run nonce must be 64 lowercase hexadecimal characters.');
}

/** Validates one required closed enum field. */
function requireEnum(event, field, allowed) {
  if (typeof event[field] !== 'string' || !allowed.includes(event[field])) {
    throw directError('PROBE_EVENT_INVALID', `${event.kind} requires ${field} from its closed vocabulary.`);
  }
}

/** Validates one required salted 64-hex hash field. */
function requireHash(event, field) {
  if (typeof event[field] !== 'string' || !DIRECT_HASH_PATTERN.test(event[field])) {
    throw directError('PROBE_EVENT_INVALID', `${event.kind} requires ${field} to be a 64 hexadecimal salted hash.`);
  }
}

/** Validates one required label/call-nonce field. */
function requirePattern(event, field, pattern) {
  if (typeof event[field] !== 'string' || !pattern.test(event[field])) {
    throw directError('PROBE_EVENT_INVALID', `${event.kind} requires a valid ${field}.`);
  }
}

/**
 * Validates the bounded [name, type] fingerprint pairs: names come only from
 * the closed allowlisted-path/redaction vocabulary and types only from the
 * closed JSON type vocabulary, so raw values (and raw sensitive key names)
 * can never hide inside a fingerprint.
 */
function requireFieldPairs(event, field) {
  const value = event[field];
  if (!Array.isArray(value) || value.length > MAXIMUM_META_FIELD_ENTRIES) {
    throw directError('PROBE_EVENT_INVALID', `${event.kind} requires ${field} to be a bounded array of name/type pairs.`);
  }
  for (const entry of value) {
    if (!Array.isArray(entry) || entry.length !== 2 || typeof entry[0] !== 'string' || typeof entry[1] !== 'string') {
      throw directError('PROBE_EVENT_INVALID', `${event.kind} ${field} entries must be bounded [name, type] pairs.`);
    }
    if (!DIRECT_METADATA_FIELD_NAMES.includes(entry[0])) {
      // The rejected name is deliberately never echoed: it may itself be the
      // sensitive value this contract exists to keep out of the evidence.
      throw directError('PROBE_EVENT_INVALID', `${event.kind} ${field} rejects a field name outside the allowlisted path vocabulary.`);
    }
    if (!DIRECT_FIELD_TYPE_NAMES.includes(entry[1])) {
      throw directError('PROBE_EVENT_INVALID', `${event.kind} ${field} requires a closed JSON type name.`);
    }
  }
}

/**
 * Validates the bounded candidate map: exactly the allowlisted candidate
 * keys, each mapping to a salted hash or null (explicit absence).
 */
function requireCandidateHashes(event) {
  const value = event.candidateHashes;
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw directError('PROBE_EVENT_INVALID', 'metadata-observed requires candidateHashes to be a bounded map.');
  }
  if (Object.keys(value).length !== DIRECT_CANDIDATE_KEYS.length) {
    throw directError('PROBE_EVENT_INVALID', `metadata-observed candidateHashes must cover exactly ${DIRECT_CANDIDATE_KEYS.join(', ')}.`);
  }
  for (const key of DIRECT_CANDIDATE_KEYS) {
    const hash = value[key];
    if (hash === null) continue;
    if (typeof hash !== 'string' || !DIRECT_HASH_PATTERN.test(hash)) {
      throw directError('PROBE_EVENT_INVALID', `metadata-observed candidateHashes.${key} must be a 64 hexadecimal salted hash or null.`);
    }
  }
}

/** The envelope keys every record carries beside its kind-specific fields. */
const ENVELOPE_KEYS = Object.freeze(['version', 'runNonce', 'sequence', 'phase', 'kind']);

/** Validates the kind-specific field allowlist of one event body. */
function validateKindFields(event) {
  const allowed = KIND_ALLOWED_FIELDS[event.kind];
  for (const key of Object.keys(event)) {
    if (ENVELOPE_KEYS.includes(key)) continue;
    if (!allowed.includes(key)) throw directError('PROBE_EVENT_INVALID', `${event.kind} rejects unknown field ${String(key)}.`);
  }
  // Per-record authentication: every handler-side record carries a 64-hex
  // HMAC over its canonical form. Presence is enforced by the append path
  // (which computes it) and by reduceDirectProbeLog (which fails closed on
  // records missing it); shape is enforced here.
  if (DIRECT_HANDLER_EVENT_KINDS.includes(event.kind)
    && event.recordMac !== undefined
    && (typeof event.recordMac !== 'string' || !DIRECT_HASH_PATTERN.test(event.recordMac))) {
    throw directError('PROBE_EVENT_INVALID', `${event.kind} recordMac must be a 64 hexadecimal HMAC.`);
  }
  switch (event.kind) {
    case 'request-sent':
      requirePattern(event, 'probeLabel', DIRECT_PROBE_LABEL_PATTERN);
      requireEnum(event, 'tool', DIRECT_TOOLS);
      requireEnum(event, 'state', DIRECT_REQUEST_STATES);
      break;
    case 'server-started':
      requireHash(event, 'serverInstanceHash');
      break;
    case 'readiness-observed':
      requireEnum(event, 'state', DIRECT_READINESS_STATES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    case 'turn-state-observed': {
      // Hashes are derived from Host-issued IDs only, never user text, so
      // they exist only when a turn was actually observed: 'not-observed'
      // and 'unknown' record no turn and must carry NO hash keys (absence,
      // never null); every other state requires both hashes.
      const turnObserved = event.state !== 'not-observed' && event.state !== 'unknown';
      if (!turnObserved) {
        if (event.threadHash !== undefined || event.turnHash !== undefined) {
          throw directError('PROBE_EVENT_INVALID', 'turn-state-observed cannot record hashes for a turn that was not observed.');
        }
      } else {
        requireHash(event, 'threadHash');
        requireHash(event, 'turnHash');
      }
      requireEnum(event, 'state', DIRECT_TURN_STATES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    }
    case 'handler-entered':
      requirePattern(event, 'probeLabel', DIRECT_PROBE_LABEL_PATTERN);
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireHash(event, 'serverInstanceHash');
      break;
    case 'metadata-observed':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireFieldPairs(event, 'fields');
      if (typeof event.fieldsTruncated !== 'boolean') {
        throw directError('PROBE_EVENT_INVALID', 'metadata-observed requires fieldsTruncated to be a boolean.');
      }
      requireCandidateHashes(event);
      requireEnum(event, 'state', DIRECT_METADATA_STATES);
      break;
    case 'hold-started':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireHash(event, 'workerHash');
      break;
    case 'trigger-sent':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireEnum(event, 'outcome', DIRECT_TRIGGER_SENT_OUTCOMES);
      break;
    case 'trigger-observed':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireEnum(event, 'outcome', DIRECT_TRIGGER_OBSERVED_OUTCOMES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    case 'handler-settled':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireEnum(event, 'outcome', DIRECT_SETTLEMENT_OUTCOMES);
      break;
    case 'worker-settled':
      requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireHash(event, 'workerHash');
      requireEnum(event, 'outcome', DIRECT_SETTLEMENT_OUTCOMES);
      break;
    case 'rpc-observed':
      requirePattern(event, 'probeLabel', DIRECT_PROBE_LABEL_PATTERN);
      // Optional until entry: the driver has no callNonce before the durable
      // join. Absence (a missing key) is the only permitted form of "none".
      if (event.callNonce !== undefined) requirePattern(event, 'callNonce', DIRECT_CALL_NONCE_PATTERN);
      requireEnum(event, 'outcome', DIRECT_RPC_OUTCOMES);
      break;
    case 'entry-action-observed':
      requirePattern(event, 'probeLabel', DIRECT_PROBE_LABEL_PATTERN);
      requireEnum(event, 'outcome', DIRECT_ENTRY_ACTION_OUTCOMES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    case 'terminal-delivered':
      requirePattern(event, 'probeLabel', DIRECT_PROBE_LABEL_PATTERN);
      requireEnum(event, 'outcome', DIRECT_DELIVERY_OUTCOMES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    case 'cleanup-observed':
      requireEnum(event, 'outcome', DIRECT_CLEANUP_OUTCOMES);
      requireEnum(event, 'source', DIRECT_SOURCES);
      break;
    default:
      throw directError('PROBE_EVENT_KIND_UNKNOWN', 'Unknown direct probe event kind.');
  }
}

/**
 * Validates one flat direct-probe record against the closed contract:
 * version, run nonce, bounded sequence, bounded phase, closed kind, and the
 * kind's exact field allowlist. Throws on any violation.
 * @param {unknown} body
 * @param {{runNonce: string}} options
 */
export function validateDirectEventRecord(body, { runNonce }) {
  requireRunNonce(runNonce);
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw directError('PROBE_EVENT_INVALID', 'The direct probe event must be an object.');
  const record = /** @type {Record<string, unknown>} */ (body);
  if (record.version !== 1) throw directError('PROBE_EVENT_INVALID', 'The direct probe event requires version 1.');
  if (record.runNonce !== runNonce) throw directError('PROBE_RUN_NONCE_FOREIGN', 'The direct probe event carries a foreign run nonce.');
  if (!Number.isSafeInteger(record.sequence) || /** @type {number} */ (record.sequence) < 0 || /** @type {number} */ (record.sequence) >= DIRECT_SEQUENCE_BOUND) {
    throw directError('PROBE_EVENT_INVALID', 'The direct probe event requires a bounded non-negative integer sequence.');
  }
  if (typeof record.phase !== 'string' || !DIRECT_PROBE_PHASES.includes(record.phase)) {
    throw directError('PROBE_EVENT_INVALID', 'The direct probe event requires a closed probe phase.');
  }
  if (typeof record.kind !== 'string' || !DIRECT_EVENT_KINDS.includes(record.kind)) {
    throw directError('PROBE_EVENT_KIND_UNKNOWN', 'Unknown direct probe event kind.');
  }
  validateKindFields(record);
}

/**
 * DRIVER-scoped durable appender: the only public append API on this module.
 * It accepts driver-side kinds only and rejects every handler-side kind
 * outright — including settlements, even when a matching entry and hold
 * already exist in the log — so a driver-originated record can never enter
 * the log as durable handler settlement. Ordering prerequisites never
 * establish who observed an event; only the writer partition does, and the
 * handler-side writer is a per-instance capability minted inside
 * `createDirectProbeServer`, not an export of this module.
 * @param {{runDirectory: string, runNonce: string, phase: string, event: object}} input
 */
export async function appendDirectProbeEvent(input) {
  const { event, ownerSecret, runDirectory } = input;
  // The driver holds the run capability secret it generated; every append —
  // driver-side included — is sealed under it.
  if (typeof ownerSecret !== 'string' || !/^[0-9a-f]{64}$/.test(ownerSecret)) {
    throw directError('PROBE_EVENT_FORBIDDEN', 'Appending requires the run capability secret; both writer processes hold it and every append is sealed under it.');
  }
  if (!event || typeof event !== 'object' || Array.isArray(event) || !DIRECT_DRIVER_EVENT_KINDS.includes(event.kind)) {
    throw directError('PROBE_EVENT_FORBIDDEN', 'This append path is driver-scoped and accepts driver-side kinds only; handler-side evidence is written exclusively by the per-instance server writer.');
  }
  // WRITER-HELD COMMIT: the driver verifies that the journal still chains
  // from its own last commit before appending, so a rolled back or diverged
  // log+journal pair can never be laundered by the next legitimate append.
  const heldCommit = driverCommitStates.get(runDirectory) ?? null;
  try {
    const result = await appendDirectProbeLogRecord({ ...input, heldCommit });
    driverCommitStates.set(runDirectory, result.commit);
    return result;
  } catch (error) {
    // ROUND 55: an ambiguous failure can reject AFTER the commit line is
    // durable — the trailing intent unlinks / directory fsyncs carry the
    // landed commit on the error. Adopt it MONOTONICALLY (only when it is
    // at or beyond the currently held commit) so the driver's witness
    // includes it and a restored earlier prefix is refused as a rollback
    // instead of being accepted.
    const ambiguousCommit = error && typeof error === 'object' ? error.commit : undefined;
    if (ambiguousCommit && (heldCommit === null || ambiguousCommit.recordCount >= heldCommit.recordCount)) {
      driverCommitStates.set(runDirectory, ambiguousCommit);
    }
    throw error;
  }
}

/**
 * Reads and validates the complete event log under the advisory event lock.
 * @param {{runDirectory: string, runNonce: string}} input
 * @returns {Promise<object[]>}
 */
export async function readDirectProbeEvents(input) {
  return readDirectProbeLog(input);
}

/**
 * TAMPER-EVIDENT reduction gate — the reducer path every legitimate driver
 * runs. Reads the validated log, and when the run contains handler-side
 * events, verifies the owner registration against the DRIVER's expected
 * capability secret and expected server pid (the spawn-time values only the
 * driver holds): any mismatch fails the whole reduction closed with
 * `PROBE_OWNER_INVALID`, so a forged owner file can make handler records
 * writable but never reducible. Runs without handler evidence reduce without
 * a capability (nothing handler-side is being claimed).
 * @param {{runDirectory: string, runNonce: string, ownerSecret?: string, ownerPid?: number}} input
 */
export async function reduceDirectProbeLog({ runDirectory, runNonce, ownerSecret, ownerPid = null, expectedFinalState }) {
  // SINGLE SNAPSHOT: readCommittedDirectProbeLog holds the advisory lock
  // once — reads the event bytes and the seal journal together, verifies the
  // journal chain and the driver final anchor, and returns only the
  // committed prefix plus the count of uncommitted trailing records.
  const { records, uncommittedCount, recovery } = await readCommittedDirectProbeLog({ runDirectory, runNonce, ownerSecret, expectedFinalState, ownerPid });
  const hasHandlerEvidence = records.some((record) => DIRECT_HANDLER_EVENT_KINDS.includes(record.kind));
  if (hasHandlerEvidence) {
    verifyDirectProbeHandlerOwnership({ runDirectory, runNonce, ownerSecret, ownerPid });
    // Per-record authentication: every handler-side record is re-MACed
    // against the driver expected secret. A swapped owner file, a replayed
    // record, or a file-appended record without the server-held secret fails
    // the whole reduction closed here.
    verifyHandlerRecordMacs(records, { ownerSecret });
  }
  const reduced = reduceAuthenticatedDirectProbeEvents(records, { runNonce });
  return { ...reduced, uncommittedCount, recovery };
}

/**
 * The durable call-nonce join: an event may reference a callNonce only when
 * exactly one handler entry in the run issued it, in the same phase, at an
 * earlier sequence. Ambiguity or absence fails closed (null).
 */
function joinedCall(callState, callNonce, phase, sequence) {
  const call = callState.byCallNonce.get(callNonce);
  if (!call) return null;
  if (call.phase !== phase || call.entrySequence >= sequence) return null;
  return call;
}

/** @param {string} message */
function joinFailed(message) {
  return directError('PROBE_JOIN_FAILED', message);
}

/**
/**
 * The guarded public reducer: driver-only event sets only. Any handler-side
 * record fails closed with PROBE_REDUCTION_UNAUTHENTICATED, directing the
 * caller to reduceDirectProbeLog.
 * @param {object[]} records
 * @param {{runNonce: string}} options
 */
export function reduceDirectProbeEvents(records, { runNonce }) {
  requireRunNonce(runNonce);
  if (records.some((record) => record && typeof record === 'object' && DIRECT_HANDLER_EVENT_KINDS.includes(record.kind))) {
    throw directError('PROBE_REDUCTION_UNAUTHENTICATED', 'The transcript contains handler-side records; use reduceDirectProbeLog, the authenticated reduction, which verifies the owner capability and per-record Macs before returning handler facts.');
  }
  return reduceAuthenticatedDirectProbeEvents(records, { runNonce });
}

/**
 * The internal reduction over an already-authenticated transcript. Called by
 * reduceDirectProbeLog after the seal, owner, and per-record Mac gates pass.
 * Missing evidence yields null or an unjoined record; it never invents
 * proof. Only durable `handler-settled`/`worker-settled` records populate
 * the settlement facts — driver records (triggers, RPC observations) are
 * never interpreted as handler or worker settlement. RPC observations are
 * classified against the durable entry join: without it the origin stays
 * `unknown`.
 * @param {object[]} records
 * @param {{runNonce: string}} options
 */
function reduceAuthenticatedDirectProbeEvents(records, { runNonce }) {
  requireRunNonce(runNonce);
  /** @type {Map<string, {probeLabel: string, callNonce: string, phase: string, entrySequence: number, metadataState: string|null, hold: {workerHash: string, sequence: number}|null, rpc: string[], handlerSettled: string|null, workerSettled: string|null}>} */
  const byCallNonce = new Map();
  const callState = { byCallNonce };
  /** @type {Map<string, {probeLabel: string, phase: string, entrySequence: number}>} */
  const byLabel = new Map();
  const requestedLabels = new Map();
  /** @type {Map<string, {probeLabel: string, phase: string, rpc: string[]}>} */
  const unjoined = new Map();
  /** @type {Set<string>} */
  const triggered = new Set();
  /** @type {string[]} */
  const phases = [];
  const requireJoin = (callNonce, phase, sequence, why) => {
    const call = joinedCall(callState, callNonce, phase, sequence);
    if (!call) throw joinFailed(why);
    return call;
  };
  const classifyRpc = (event, call) => {
    if (event.outcome === 'rpc-rejected') return 'rpc-rejected';
    if (event.outcome === 'not-observed') return 'not-observed';
    const entered = Boolean(call);
    if (event.outcome === 'error-result') return entered ? 'error-result-handler-entered' : 'error-result-unknown-origin';
    return entered ? 'success-handler-entered' : 'success-unknown-origin';
  };
  for (const [index, record] of records.entries()) {
    validateDirectEventRecord(record, { runNonce });
    if (record.sequence !== index) throw directError('PROBE_SEQUENCE_INVALID', 'The event sequence contains an out-of-order record.');
    if (!phases.includes(record.phase)) phases.push(record.phase);
    const event = record;
    switch (event.kind) {
      case 'request-sent': {
        if (requestedLabels.has(event.probeLabel)) throw directError('PROBE_LABEL_DUPLICATE', 'The event sequence contains a duplicate request for one probe label.');
        requestedLabels.set(event.probeLabel, { phase: event.phase, sequence: event.sequence, dispatched: event.state === 'sent' });
        break;
      }
      case 'handler-entered': {
        const requested = requestedLabels.get(event.probeLabel);
        if (!requested || requested.phase !== event.phase) {
          throw directError('PROBE_ORDER_INVALID', 'Handler entry requires a prior request-sent for the same label in the same phase.');
        }
        if (!requested.dispatched) {
          // A request the driver recorded as not-sent never dispatched, so it
          // can never be the prerequisite of a handler entry: a log whose
          // only request for the label is `not-sent` fails the join.
          throw directError('PROBE_ORDER_INVALID', 'Handler entry requires a dispatched request (state sent); a not-sent request is a missing prerequisite.');
        }
        if (requested.sequence >= event.sequence) {
          throw directError('PROBE_ORDER_INVALID', 'Handler entry must follow its request.');
        }
        if (byCallNonce.has(event.callNonce)) throw directError('PROBE_ENTRY_DUPLICATE', 'The event sequence contains a duplicate handler entry for one call.');
        if (byLabel.has(event.probeLabel)) throw directError('PROBE_LABEL_DUPLICATE', 'One probe label must identify exactly one call.');
        const call = {
          probeLabel: event.probeLabel,
          callNonce: event.callNonce,
          phase: event.phase,
          entrySequence: event.sequence,
          metadataState: null,
          hold: null,
          rpc: [],
          handlerSettled: null,
          handlerSettledSequence: null,
          workerSettled: null,
          workerSettledSequence: null,
        };
        byCallNonce.set(event.callNonce, call);
        byLabel.set(event.probeLabel, { probeLabel: event.probeLabel, phase: event.phase, entrySequence: event.sequence });
        break;
      }
      case 'metadata-observed': {
        const call = joinedCall(callState, event.callNonce, event.phase, event.sequence);
        if (!call) throw directError('PROBE_ORDER_INVALID', 'Metadata observation requires a prior handler entry in the same phase.');
        if (call.metadataState !== null) throw directError('PROBE_ORDER_INVALID', 'The event sequence contains a duplicate metadata observation.');
        call.metadataState = event.state;
        break;
      }
      case 'hold-started': {
        const call = joinedCall(callState, event.callNonce, event.phase, event.sequence);
        if (!call) throw directError('PROBE_ORDER_INVALID', 'Hold start requires a prior handler entry in the same phase.');
        if (call.hold) throw directError('PROBE_ORDER_INVALID', 'The event sequence contains a duplicate hold start.');
        call.hold = { workerHash: event.workerHash, sequence: event.sequence };
        break;
      }
      case 'trigger-sent': {
        requireJoin(event.callNonce, event.phase, event.sequence, 'A driver trigger may not name a call nonce without a durable entry join.');
        triggered.add(event.callNonce);
        break;
      }
      case 'trigger-observed': {
        requireJoin(event.callNonce, event.phase, event.sequence, 'A driver trigger observation may not name a call nonce without a durable entry join.');
        if (!triggered.has(event.callNonce)) throw directError('PROBE_ORDER_INVALID', 'A trigger observation requires a prior trigger-sent for the same call.');
        break;
      }
      case 'rpc-observed': {
        // Attribution requires BOTH halves of the unique-label join: the RPC
        // must carry a prior request-sent for its own label in the same
        // phase, AND the durable entry behind its callNonce must carry that
        // exact label. A response for label B naming call A's nonce fails
        // closed to unknown-origin — it can never become handler-entered.
        const requested = requestedLabels.get(event.probeLabel);
        const requestJoins = Boolean(requested
          && requested.dispatched
          && requested.phase === event.phase
          && requested.sequence < event.sequence);
        let call = null;
        if (event.callNonce !== undefined) {
          const joined = requireJoin(event.callNonce, event.phase, event.sequence, 'A driver RPC observation may not name a call nonce without a durable entry join.');
          call = requestJoins && joined.probeLabel === event.probeLabel ? joined : null;
        }
        const classification = classifyRpc(event, call);
        if (call) call.rpc.push(classification);
        else {
          const key = `${event.phase}\u0000${event.probeLabel}`;
          if (!unjoined.has(key)) unjoined.set(key, { probeLabel: event.probeLabel, phase: event.phase, rpc: [] });
          unjoined.get(key).rpc.push(classification);
        }
        break;
      }
      case 'handler-settled': {
        const call = joinedCall(callState, event.callNonce, event.phase, event.sequence);
        if (!call) throw directError('PROBE_ORDER_INVALID', 'Handler settlement requires a prior handler entry in the same phase.');
        if (call.handlerSettled !== null) throw directError('PROBE_SETTLEMENT_DUPLICATE', 'The event sequence contains a duplicate handler settlement.');
        call.handlerSettled = event.outcome;
        call.handlerSettledSequence = event.sequence;
        break;
      }
      case 'worker-settled': {
        const call = joinedCall(callState, event.callNonce, event.phase, event.sequence);
        if (!call || !call.hold) throw directError('PROBE_ORDER_INVALID', 'Worker settlement requires a prior hold start in the same phase.');
        if (call.workerSettled !== null) throw directError('PROBE_SETTLEMENT_DUPLICATE', 'The event sequence contains a duplicate worker settlement.');
        if (call.hold.workerHash !== event.workerHash) throw directError('PROBE_WORKER_MISMATCH', 'Worker settlement does not match the held synthetic worker.');
        call.workerSettled = event.outcome;
        call.workerSettledSequence = event.sequence;
        break;
      }
      default:
        // server-started, readiness-observed, turn-state-observed,
        // entry-action-observed, terminal-delivered, cleanup-observed are
        // contract-validated above; their reduction belongs to later tasks.
        break;
    }
  }
  return {
    phases,
    calls: [...byCallNonce.values()].map((call) => ({
      probeLabel: call.probeLabel,
      callNonce: call.callNonce,
      phase: call.phase,
      entrySequence: call.entrySequence,
      metadataState: call.metadataState,
      rpc: call.rpc,
      handlerSettled: call.handlerSettled,
      handlerSettledSequence: call.handlerSettledSequence,
      workerSettled: call.workerSettled,
      workerSettledSequence: call.workerSettledSequence,
    })),
    unjoined: [...unjoined.values()],
  };
}

/**
 * Validates the closed decision record (the frozen result format): exact
 * provenance fields, evidence digest/count, and gates G1-G4, each with a
 * closed status, bounded reason code, and evidence references. Unknown
 * fields fail closed; a mismatched provenance run nonce fails closed.
 * @param {unknown} body
 * @param {{runNonce?: string|null}} [options]
 */
export function validateDirectResultRecord(body, { runNonce = null } = {}) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw directError('PROBE_RESULT_INVALID', 'The direct probe result record must be an object.');
  const record = /** @type {Record<string, unknown>} */ (body);
  const expectedKeys = ['evidence', 'gates', 'provenance', 'version'];
  for (const key of Object.keys(record)) {
    if (!expectedKeys.includes(key)) throw directError('PROBE_RESULT_INVALID', `The result record rejects unknown field ${key}.`);
  }
  if (expectedKeys.some((key) => !(key in record))) throw directError('PROBE_RESULT_INVALID', 'The result record requires version, provenance, evidence, and gates.');
  if (record.version !== 1) throw directError('PROBE_RESULT_INVALID', 'The result record requires version 1.');
  const provenance = record.provenance;
  if (!provenance || typeof provenance !== 'object' || Array.isArray(provenance)) throw directError('PROBE_RESULT_INVALID', 'The result record requires a provenance object.');
  for (const key of Object.keys(provenance)) {
    if (!DIRECT_PROVENANCE_FIELDS.includes(key)) throw directError('PROBE_RESULT_INVALID', `The result provenance rejects unknown field ${key}.`);
  }
  for (const key of DIRECT_PROVENANCE_FIELDS) {
    if (!DIRECT_OPTIONAL_PROVENANCE_FIELDS.includes(key) && !(key in provenance)) {
      throw directError('PROBE_RESULT_INVALID', `The result provenance requires ${key}.`);
    }
  }
  requireRunNonce(provenance.runNonce);
  if (runNonce !== null && provenance.runNonce !== runNonce) throw directError('PROBE_RUN_NONCE_FOREIGN', 'The result record carries a foreign run nonce.');
  for (const key of ['codexBinaryDigest', 'schemaDigest']) {
    if (typeof provenance[key] !== 'string' || !DIRECT_HASH_PATTERN.test(provenance[key])) {
      throw directError('PROBE_RESULT_INVALID', `The result provenance requires ${key} to be a 64 hexadecimal digest.`);
    }
  }
  if (typeof provenance.sourceCommit !== 'string' || !DIRECT_SOURCE_COMMIT_PATTERN.test(provenance.sourceCommit)) {
    throw directError('PROBE_RESULT_INVALID', 'The result provenance requires sourceCommit to be a 40 hexadecimal commit digest.');
  }
  for (const key of ['codexVersion', 'platform', 'sdkVersion']) {
    if (!isBoundedText(provenance[key])) throw directError('PROBE_RESULT_INVALID', `The result provenance requires bounded text for ${key}.`);
  }
  for (const key of ['model', 'effort']) {
    if (key in provenance && !isBoundedText(provenance[key])) {
      throw directError('PROBE_RESULT_INVALID', `The result provenance requires bounded text for ${key} when present.`);
    }
  }
  if ('configurationDigest' in provenance
    && (typeof provenance.configurationDigest !== 'string' || !DIRECT_HASH_PATTERN.test(provenance.configurationDigest))) {
    throw directError('PROBE_RESULT_INVALID', 'The result provenance requires configurationDigest to be a 64 hexadecimal digest of the sanitized configuration.');
  }
  if (!DIRECT_FIXTURE_MODES.includes(provenance.fixtureMode)) throw directError('PROBE_RESULT_INVALID', 'The result provenance requires a closed fixture mode.');
  const evidence = record.evidence;
  if (!evidence || typeof evidence !== 'object' || Array.isArray(evidence)) throw directError('PROBE_RESULT_INVALID', 'The result record requires an evidence object.');
  for (const key of Object.keys(evidence)) {
    if (key !== 'digest' && key !== 'count') throw directError('PROBE_RESULT_INVALID', `The result evidence rejects unknown field ${key}.`);
  }
  if (!('digest' in evidence) || !('count' in evidence)) throw directError('PROBE_RESULT_INVALID', 'The result evidence requires a digest and a count.');
  if (typeof evidence.digest !== 'string' || !DIRECT_HASH_PATTERN.test(evidence.digest)) {
    throw directError('PROBE_RESULT_INVALID', 'The result evidence requires digest to be a 64 hexadecimal digest.');
  }
  if (!Number.isSafeInteger(evidence.count) || /** @type {number} */ (evidence.count) < 0) {
    throw directError('PROBE_RESULT_INVALID', 'The result evidence requires a non-negative integer count.');
  }
  const gates = record.gates;
  if (!gates || typeof gates !== 'object' || Array.isArray(gates)) throw directError('PROBE_RESULT_INVALID', 'The result record requires a gates object.');
  for (const key of Object.keys(gates)) {
    if (!DIRECT_GATE_KEYS.includes(key)) throw directError('PROBE_RESULT_INVALID', `The result gates reject unknown gate ${key}.`);
  }
  for (const key of DIRECT_GATE_KEYS) {
    const gate = gates[key];
    if (!gate || typeof gate !== 'object' || Array.isArray(gate)) throw directError('PROBE_RESULT_INVALID', `The result requires a ${key} gate.`);
    for (const gateKey of Object.keys(gate)) {
      if (gateKey !== 'status' && gateKey !== 'reasonCode' && gateKey !== 'evidenceRefs') {
        throw directError('PROBE_RESULT_INVALID', `The ${key} gate rejects unknown field ${gateKey}.`);
      }
    }
    if (!DIRECT_GATE_STATUSES.includes(gate.status)) throw directError('PROBE_RESULT_INVALID', `The ${key} gate requires a closed status.`);
    if (typeof gate.reasonCode !== 'string' || !DIRECT_REASON_CODE_PATTERN.test(gate.reasonCode)) {
      throw directError('PROBE_RESULT_INVALID', `The ${key} gate requires a bounded reason code.`);
    }
    if (!Array.isArray(gate.evidenceRefs)) throw directError('PROBE_RESULT_INVALID', `The ${key} gate requires an evidenceRefs array.`);
    for (const ref of gate.evidenceRefs) {
      if (typeof ref !== 'string' || !DIRECT_EVIDENCE_REF_PATTERN.test(ref)) {
        throw directError('PROBE_RESULT_INVALID', `The ${key} gate evidence references must be kind@sequence tokens.`);
      }
    }
  }
  return record;
}
